### ISSUE TITLE
Organize the list of metrics for selection in sub-lists. 

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#12]
Tentative organization suggested (some metrics may not appear right now). The name of the list is followed by the list with the metrics. The "monthly/accum" means that both metric versions should appear.

New Pages (monthly / accum)
	- Pages
	- Articles
	- Article talk
	- User Talk
	- Others

Edits (monthly / accum)
	- In pages (old "General")
	- In articles
	- In article talk
	- In user Talk
	- Others (?)
	- Edited pages (probably only non accum)
	- Edited articles
	
Users (monthly / accum)
	- New users
	- New anonymous users
	- New registered users
	- Active users
	- Active anonymous users
	- Active registered users
	
Ratios (monthly / accum)	
	- Page edits per user
	- Article edits per user
	- Edits per pages (edits understood as page edits)
	- Edits per articles (edits understood as article edits)
	
	
Think whether it is possible to elegantly show the accumulated and non accumulated metrics without  duplicate the number of lines (elements). Perhaps, the elements could be inside a "table" with three columns: name and the column with non accum checkboxes and the column with accumulated checkboxes. If one metric has no "accumulated" version no checkbox appears in that column.	

Think whether we should use the word "accumulated" or "cumulative".

**Comment by Akronix** [comment]
I'd rather start showing both monthly and accum versions in the list, and re-think further its presentation for the next iteration.

**Comment by javiag** [comment]
As you wish.
