### ISSUE TITLE
Remove bot activity from the metrics

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#18]
Since the tool is interested in analyzing/visualizing human activity in wikis, metrics must not consider bots or bot activity. 

Hence, bots should be removed from users counts (active users, new users, new registered users, etc), from activity counts (gloabl edits, article edits, edits in user talk, edits in article talk, pages edited monthly...)  and ratios (e.g. in edits per user, bot activity should not be taken into account into the numerator and bots should not be counted in the denominator).

**Comment by javiag** [comment]
My only concern is whether a page created by a bot should be considered. I guess it should be, because it may be later edited by human participants.

**Comment by Akronix** [comment]
> My only concern is whether a page created by a bot should be considered. I guess it should be, because it may be later edited by human participants.

You mean that whether it should count in the "New pages" metric or whether the subsequent non-bots edits on it should be counted?

**Comment by javiag** [comment]
I meant that both things (page created by a bot and the subsequent non-bot edits) should be carefully considered.  

If we finally create some metrics for bot activity and remove bots from the rest of the metrics, then we have the solution for this issue: each event is counted in its respective metric.
