### ISSUE TITLE
Bot metrics

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#19]
It is not a priority in WikiChron, but bot activity could be shown using a few metrics;

- Bot edits (considering edits in general and not particularizing whether they edit articles or not) 
- Bot users

**Comment by Akronix** [comment]
@javiag do you find this still interesting?

**Comment by javiag** [comment]
Not particularly, as long as we are filtering out bot users and bot edits. Can you refresh my mind?

In any case, bot metrics are definitely low priority, but still it will be interesting. Do you remember the talk about bot edits at opensym 18? Bots are an issue.

**Comment by Akronix** [comment]
Okay then, shall we keep this open  so we implement it at some point? Because if it doesn't seem really interesting I prefer to close this.

**Comment by javiag** [comment]
OK! Let's close it.
