### ISSUE TITLE
The slider behaviour should be refined

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#22]
There are some issues that could be refined. Namely:

- The endpoint of the slider should have a tag.
- The tags in absolute dates should not be every 5 elements, but every 6 elements or every 12 elements (in this way, they work in a yearly basis). Furthermore, to make them correspond with the vertical lines in the plot, they should mark the beginning of the year (January)
- Consecutive date tags may colapse in some cases. Consider rotating the tags, if possible.  
- It would be nice to see the date with the current position, when you are sliding the handle.

**Comment by Akronix** [comment]
For the last point:

> * It would be nice to see the date with the current position, when you are sliding the handle.

We could add a small text block to the right of the text that reads: "Time interval (months)", showing the current time interval selection. What do you think about it @javiag ?

**Comment by javiag** [comment]
Sounds good! Thanks.
