### ISSUE TITLE
Add info about metrics computation, assumptions and decisions taken

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#25]
The computation of the metrics assume several aspects that should be clarified somewhere in wikichron, probably and info page. 

A (probably) non-exhaustive list of aspects and decisions taken that should be clarified/explained are:

- Definition of page, article, user, active user, anonymous user, contribution (are there any exception to the definition? how are they computed?) 
- How are the edits (and other metrics) of anonymous users computed (grouped by IP address?)
- What happens with bots edits (they are removed from the metrics)? How are bots identified?
- How are the montly counts computed specially in the case of "relative" dates? By natural months or by "relative" months? 
- Mathematical formula of each and every metric computed

**Comment by Akronix** [comment]
Done in the [WikiChron's wiki](https://github.com/Grasia/WikiChron/wiki/Basic-concepts).
Maybe you want to take a look at the [Time axis options](https://github.com/Grasia/WikiChron/wiki/Basic-concepts#time-axis-options) section.
