### ISSUE TITLE
Show metrics description on hover

### ISSUE THREAD

**Issue by Akronix** [Grasia/WikiChron#31]
Display a short metric description when mouse is over the metrics of the list.
Use html title attribute for this.

**Comment by Akronix** [comment]
@javiag What's the priority of this?
The objective is to have something like this for the metric checklist: https://www.w3schools.com/code/tryit.asp?filename=FP4DVIVM9M4D

**Comment by javiag** [comment]
Definitely not to be done in the next 10 days :)

**Comment by javiag** [comment]
It is related with #25 as here we will show a short explanation.
I should draft the texts for #31 and #25 and then we can iterate from there until we have something we feel OK with.

**Comment by Akronix** [comment]
The texts are already done, see: https://github.com/Grasia/WikiChron/blob/master/lib/metrics/metrics_generator.py#L19
