### ISSUE TITLE
[New metric] Percentage of anonymous edits

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#32]
The percentage is  computed 100*(edits_by_anonymous_users / edits) 

It would be interesting as a monthly metric (considering only the edits of a each month) and the accumulative version (considering the edits from the creation of the wiki until the end of each month).

**Comment by Akronix** [comment]
I've set 0 when total edits is 0 in order to avoid gaps in the plotted graphs.

**Comment by javiag** [comment]
Please, whenever possible change it to real gaps, as a zero has a different meaning.
