### ISSUE TITLE
Clarify names of ratio metrics

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#33]
Use clearer names

**Comment by Akronix** [comment]
What names do you propose?

**Comment by javiag** [comment]
### New pages
 In  the "New pages" section, perhaps we can use "New pages" and "Total pages", in this way we omit the verbose and misleading "monthly" and "accumulated". We have a cleaner and clearer wording. IDEM with articles. So the new names (in a new order) would be:
- New pages
- New articles
- Pages edited (*)
- Articles edited (*)
- Total pages
- Total articles

(*) Here I would ommit "monthly", assuming that no-total means the old "monthly".  Besides, all the totals at the bottom of the lists. Presumably in the new UI they are supposed to be divided in two subpanels.

### Edits
The same can be done with the metrics in the "Edits" section. New names in a new order
- Edits in pages (**)
- Edits in articles
- Edits in article talk 
- Edits in user talk 
- Total edits in pages (**)
- Total edits in articles

(**) Instead of "Global edits", use "Edits in pages", in this way we use the same term/concept used in the "New Pages" section: page as a superset of articles. Even we can say "Edits (in pages)"

### Users
In the case of the "Users" (different order again): 
- New users
- New registered users
- Active users
- Active anonymous users (***)
- Total users
- Total registered users
- Total anonymous users

(***) This is the actual meaning of "monthly anonymous users", I understand it means "active anonymous users" and no "new anonymous users". However, now I think that in this list we could add some metrics to have the same 3 concepts for the 3 kinds of users.  The new list would be (new metrics in italics):
- New users
- New registered users
- _New anonymous users (new metric!)_
- Active users
- _Active registered users  (new metric!)_
- Active anonymous users (*)
- Total users
- Total registered users
- Total anonymous users

If you  (@Akronix) think the same, then create a new issue accordingly.

Moreover, "anon." is used as abbreviation of anonymous (check [here](https://www.abbreviations.com/abbreviation/anonymous)) and "reg." for registered. 


### Ratios 
Again a different order. 
- Edits per user
- Article edits per user
- Edits per page (****) (*****)
- Anonymous article edits (%)  (******)
- _Total edits per user (new metric!)_
- Total article edits per user
- Total edits per page (****) (*****)
- Total anonymous article edits (%) (******)

(****) I think that after "per" you don't use plural. We used it to reinforce the "accumulated" notion, but it is misleading, I guess.

(*****) I think we can stick with the "edits per page" in order to imply that both the numerator and the denominator is monthly. The cumulative version of the metric named "Total edits per page" hopefully will imply total in both sides.

(******) They are article edits or "global" edits, i.e. edits a secas.

### Distribution of Participation 

The problem of the proposed use of "none" and "total" arises in this section, where we don't want to add a total or a cumulative.

My proposal is to use "cumulative" in the title: "Cumulative work distribution". I know that the problem arise if we create "monthly" version of the metrics, but this could be added only in the new interface. Or in this one adding a new section "Monthly work distribution".

Besides that, we have to use the same names that we use in the article so the names should be (again different order):

- Gini coefficient
- 10:90 ratio
-  Top contributors prctl. top/5
-  Top contributors prctl. 5/10
-  Top contributors prctl. 10/20
-  Top contributors prctl. top/10
-  Top contributors prctl. top/20


I just realized that this notation is misleading, since we reverse the traditional order of the percentiles. That is, when talking about percentiles, by 5, 10, 20 you mean the "left" tail of the distribution, but here we mean the "right" tail. In the paper is explained, but still perhaps it is not intuitive. Maybe here we should ask for help to some natives.

Furthermore, I am considering whether we could remove the last two metrics, because the value they take is usually huge and the distance between the top and the "10th" and the "20th" contributor does not tell us nothing about what is happening between them. We do not use them in the article.

**Comment by Akronix** [comment]
@javiag the monthly anonymous users metric refers to the quantity of new anonymous users who has appeared every month...Actually it should be _Monhtly new anon. users_ and with the new notation it would become New Anon. users.

Therefore, the _new_ metric to develop will be "Active anon. users" and the other will just have to be renamed.
