### ISSUE TITLE
Refine time axis selection

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#4]
Relative/Absolute dates should be a switch in the right side, probably close to the slider with the time range.

Both time series should be computed at the same time (when the COMPARE button is pushed) and the switch should be on the right side to make possible the user change between both possible views whenever he or she wants.

In my opinion, if you visualize just one wiki the default mode should be absolute dates, but if you compare more than one the default mode should be relative. By "default mode" I mean what it should be shown when you push COMPARE.  The user should not anticipate how he wants to show the time series before, but casually change from one to other in case he or she wants it.

Regarding the slider, it changes with the absolute/relative selection.
- The slider numbers should change from integers to dates or viceversa.
- The handles should be reset to all the time range. Probably more sophisticated behavior is not needed.

**Comment by Akronix** [comment]
Done in 8334f89c4f16e83beec903b956f784dc8ffff394
