### ISSUE TITLE
Classic -> wiki labels overlap over a title

### ISSUE THREAD

**Issue by FRYoussef** [Grasia/WikiChron#71]
If you select a lot of labels, them will overlap over the next title.

![imagen](https://user-images.githubusercontent.com/25131320/56097581-ab467d00-5ef6-11e9-92a3-ee03b841b6c2.png)

**Comment by javiag** [comment]
It happens both in the wiki and metric selection.

The label should read "Your metric selection:"

**Comment by Akronix** [comment]
Fixed with the new redesign of the selection screen.
