### ISSUE TITLE
Check the coherence of the term and computations of "active users"

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#91]
As far as I know, we are using the term users in a way that includes anonymous AND registered users. 

Furthermore, the users active each month are known as active users. 

With that in mind, the coherence of the names should be checked.

So the old names >> new names are:

    Edits per user >>  Edits per active user
    Article edits per user >>     Article edits per active user

I think that the problem is just in the names, because the computations seem correspond to active users (including both registered users and anonymous users grouped by IP). 

Anyway, it should be validated that both the naming and the computation remain coherent in the present metrics, but also in the new metrics to be included (wikichron mono version).

**Comment by Akronix** [comment]
Hum, but still see that "Edits per user" is different from "Edits per active user" in the sense that the first one counts all the users that have edited ever since while the second one would rate all the edits divided by the number of users active _only that month_.

**Comment by javiag** [comment]
Is really like that? Edits per user is monthly edits divided by the number of "users that have edited ever since"? I think you are wrong now, we are talking about the "monthly" metric, the one without the "total" in the name.  Hence, it should be monthly edits by monthly active users. 

In the "total" or "cumulative" version, then it should be total edits up to month x divided by total users up to month x. 

And by users we mean both anonymous (by IP) plus registered users.

Am I right?

Sorry for the confusion.

**Comment by Akronix** [comment]
You're absolutely right. Apologize **me** for the confusion.
