### ISSUE TITLE
Deletion of redundant metrics

### ISSUE THREAD

**Issue by javiag** [Grasia/WikiChron#92]
Now that we are going to have WikiChron monowiki, the following metrics are redundant and should be deleted:
- Active users with > 4 edits

- Active users with > 24 edits

- Active users with > 99 edits

I know that they are available in WikiChron compare, but I think there is no point in comparing them for different wikis. and that less metrics is sometimes better :)

**Comment by Akronix** [comment]
I thought about it too, and yes, they are quite dirtying the metrics selection.
So shall we remove them from the "compare" version as well?

**Comment by javiag** [comment]
Yep
